version: "3"
services:
  foo-service:
    build: .
    links:
#    depends_on:
    - rabbitmq-server
    restart: on-failure

  rabbitmq-server:
    image: "rabbitmq:3-management"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"

