version: "3"
services:
  rabbitmq-server:
    image: "rabbitmq"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"

  foo-service:
    build: .
#    links:
    depends_on:
      - rabbitmq-server
    restart: on-failure


